// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdFTFGg6gYq6xraTWBsQvvzSz-a4X6uB0',
    appId: '1:663177712483:web:9ecaae0f6a164209db3956',
    messagingSenderId: '663177712483',
    projectId: 'network-27f13',
    authDomain: 'network-27f13.firebaseapp.com',
    storageBucket: 'network-27f13.firebasestorage.app',
    measurementId: 'G-LD231DSZFV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOeuGtWWsM4KJxSUF3gDmYgE2yEw1dytw',
    appId: '1:663177712483:android:aaace92f69f75f13db3956',
    messagingSenderId: '663177712483',
    projectId: 'network-27f13',
    storageBucket: 'network-27f13.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1nk4MvWpTndvL0E2rnqTow4425StB1KM',
    appId: '1:663177712483:ios:022dc856f6ea14dddb3956',
    messagingSenderId: '663177712483',
    projectId: 'network-27f13',
    storageBucket: 'network-27f13.firebasestorage.app',
    iosBundleId: 'com.example.nutonium',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1nk4MvWpTndvL0E2rnqTow4425StB1KM',
    appId: '1:663177712483:ios:022dc856f6ea14dddb3956',
    messagingSenderId: '663177712483',
    projectId: 'network-27f13',
    storageBucket: 'network-27f13.firebasestorage.app',
    iosBundleId: 'com.example.nutonium',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdFTFGg6gYq6xraTWBsQvvzSz-a4X6uB0',
    appId: '1:663177712483:web:62d93beccda565f2db3956',
    messagingSenderId: '663177712483',
    projectId: 'network-27f13',
    authDomain: 'network-27f13.firebaseapp.com',
    storageBucket: 'network-27f13.firebasestorage.app',
    measurementId: 'G-D351LYZVBL',
  );
}
